# Python на минималках
FROM python:3.11-slim

WORKDIR /app

# Копируем скрипт и сертификаты из Mosquitto
COPY config/mqtt_scripts/mqtt_mode_meta_checker.py /app/mqtt_mode_meta_checker.py
COPY config/mosquitto/certs /app/certs

# Устанавливаем зависимости
RUN pip install --no-cache-dir paho-mqtt

CMD ["python", "/app/mqtt_mode_meta_checker.py"]
